version: '3'
services:
  app:
    build: .
    command: "npm run start"
    ports:
      - "3000:3000"
    networks:
      - app-network

  data-generator:
    build: .
    command: "npm run generate-data"
    depends_on:
      - app
    networks:
      - app-network

  test-runner:
    build: .
    command: "npm run test"
    depends_on:
      - app
    environment:
      - BASE_URL=http://app:3000
    networks:
      - app-network
    volumes:
      - ./playwright-report:/app/playwright-report

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - app
    networks:
      - app-network

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    depends_on:
      - prometheus
    networks:
      - app-network
    volumes:
      - grafana-storage:/var/lib/grafana

networks:
  app-network:

volumes:
  grafana-storage:
