name: CI Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Images
        run: |
          docker-compose build
          # Optionally, push images if needed
          # docker-compose push
          
      - name: Start Services
        run: docker-compose up -d

      - name: Wait for Services to Be Ready
        run: |
          echo "Waiting for services to start..."
          sleep 30  # Adjust as needed

      - name: Run Tests
        run: docker-compose run test-runner

      - name: Shutdown Services
        run: docker-compose down

      - name: Upload Test Report
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report
