name : CI Pipeline

on:
  push:
    branches: [ master]
  pull_request:
    branches: [ master ]

jobs:
   build-and-test:
     runs-on: ubuntu-latest

     steps:
       - name: Checkout code
         uses: actions/checkout@v3
       
       - name: Set up Node.js
         uses: actions/setup-node@v3
         with:
           node-version: '16'
        
       - name: Install dependencies
         run: npm install
       
       -name: Build the project
         run: npm run build
      
       - name: Start the application
         run: npm start &
         env:
            PORT: 3000
      

      - name: Wait for server to be ready
        run: |
          for i in {1..10}; do
            if nc -zv localhost 3000; then
                echo "Server is up!"
                break
            else
               echo "Waiting for server..."
               sleep 3
            fi
          done
      -name: Run tests
        run: npm run test